### ISSUE TITLE
Live-preview server

### ISSUE THREAD

**Issue by 97-109-107** [metakirby5/whizkers#3]
Dear @metakirby5 & @fullsalvo 

I moved from themer to whizkers and having discovered the simplicity of this model decided to write a utility that would fix a problem I've had for a long time - previewing all the Xresources templates I had. Here's my naiive solution:

https://github.com/97-109-107/whizkers-server

Thanks for sharing whizkers and wz-utils - they work great.

I'm very open to pull request or suggestions or perhaps merging into whizkers? Or just tighter coupling?

**Comment by metakirby5** [comment]
This is an awesome idea! I love it - I'll add it to a resources section in the whizkers readme when I get the chance. I don't think it should be merged into whizkers, as it makes assumptions about how you're using it. I want to keep whizkers as an open-ended templater, not just for themes.

There are a few issues I found in a few minutes of testing, and I'll open them as issues in your repo later. Again, thanks so much for contributing! I can see myself using this a lot :)
